/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "connection.h"

bool_t
xdr_row (XDR *xdrs, row *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->row_val, (u_int *) &objp->row_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix (XDR *xdrs, matrix *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->matrix_val, (u_int *) &objp->matrix_len, ~0,
		sizeof (row), (xdrproc_t) xdr_row))
		 return FALSE;
	return TRUE;
}
