/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "connection.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "gauss.h"
#include "gauss_process.h"
#include "macierz_struct.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

char *result_char_ptr;  // dla echo_char
char *result_string_ptr; // dla echo_string


char ** echo_char_1_svc(char *argp, struct svc_req *rqstp) {
    static char result[100];
    snprintf(result, sizeof(result), "Otrzymano znak: %c", *argp);
    result_char_ptr = result;
    return &result_char_ptr;
}


char ** echo_string_1_svc(char **argp, struct svc_req *rqstp) {
    static char result[256];  // bufor wynikowy
    snprintf(result, sizeof(result), "Otrzymano string: %s", *argp);
    result_string_ptr = result;
    return &result_string_ptr;
}

char **gauss_matrix_1_svc(matrix *m, struct svc_req *rqstp) {
    static char result[4096];      // bufor na wynik
    static char *result_ptr;       // wskaźnik do zwracanego bufora

    result[0] = '\0';

	matrix mat_copy = matrix_deep_copy(m); //jedna kopia potrzebna do wersji równoległej by nie korzystać z rozwiązanej już macierzy

    char buf1[2048], buf2[2048];

    // Funkcje muszą zapisywać swoje wyniki do stringów
    gaussianElimination(m, buf1, sizeof(buf1));
    gaussianElimination_p(&mat_copy, buf2, sizeof(buf2));

    // Scalanie do jednego stringa
    snprintf(result, sizeof(result), "%s\n%s", buf1, buf2);

	matrix_free(&mat_copy);
    result_ptr = result;
    return &result_ptr;
}

matrix* gauss_matrix_print_1_svc(matrix *m, struct svc_req *rqstp)
{
    matrix* result = malloc(sizeof(matrix)); // allocate on heap
    if (!result) return NULL; // handle allocation failure

    *result = matrix_deep_copy(m); // copy content
    gaussianElimination(result, NULL, 0);

	//print_gauss_solutions(result);

    return result; // safe to return
}

matrix* gauss_matrix_print_process_1_svc(matrix *m, struct svc_req *rqstp)
{
    matrix* result = malloc(sizeof(matrix)); // allocate on heap
    if (!result) return NULL; // handle allocation failure

    *result = matrix_deep_copy(m); // copy content
    gaussianElimination_p(result, NULL, 0);

	//print_gauss_solutions(result);

    return result; // safe to return
}

static void
connection_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char echo_char_1_arg;
		char *echo_string_1_arg;
		matrix gauss_matrix_1_arg;
		matrix gauss_matrix_print_1_arg;
		matrix gauss_matrix_print_process_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case echo_char:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) echo_char_1_svc;
		break;

	case echo_string:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) echo_string_1_svc;
		break;

	case gauss_matrix:
		_xdr_argument = (xdrproc_t) xdr_matrix;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) gauss_matrix_1_svc;
		break;

	case gauss_matrix_print:
		_xdr_argument = (xdrproc_t) xdr_matrix;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) gauss_matrix_print_1_svc;
		break;

	case gauss_matrix_print_process:
		_xdr_argument = (xdrproc_t) xdr_matrix;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) gauss_matrix_print_process_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CONNECTION_PROG, CONNECTION_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CONNECTION_PROG, CONNECTION_VERS, connection_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CONNECTION_PROG, CONNECTION_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CONNECTION_PROG, CONNECTION_VERS, connection_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CONNECTION_PROG, CONNECTION_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
