/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONNECTION_H_RPCGEN
#define _CONNECTION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int row_len;
	double *row_val;
} row;

typedef struct {
	u_int matrix_len;
	row *matrix_val;
} matrix;

#define CONNECTION_PROG 0x20000002
#define CONNECTION_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define echo_char 1
extern  char ** echo_char_1(char *, CLIENT *);
extern  char ** echo_char_1_svc(char *, struct svc_req *);
#define echo_string 2
extern  char ** echo_string_1(char **, CLIENT *);
extern  char ** echo_string_1_svc(char **, struct svc_req *);
#define gauss_matrix 3
extern  char ** gauss_matrix_1(matrix *, CLIENT *);
extern  char ** gauss_matrix_1_svc(matrix *, struct svc_req *);
#define gauss_matrix_print 4
extern  matrix * gauss_matrix_print_1(matrix *, CLIENT *);
extern  matrix * gauss_matrix_print_1_svc(matrix *, struct svc_req *);
#define gauss_matrix_print_process 5
extern  matrix * gauss_matrix_print_process_1(matrix *, CLIENT *);
extern  matrix * gauss_matrix_print_process_1_svc(matrix *, struct svc_req *);
extern int connection_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define echo_char 1
extern  char ** echo_char_1();
extern  char ** echo_char_1_svc();
#define echo_string 2
extern  char ** echo_string_1();
extern  char ** echo_string_1_svc();
#define gauss_matrix 3
extern  char ** gauss_matrix_1();
extern  char ** gauss_matrix_1_svc();
#define gauss_matrix_print 4
extern  matrix * gauss_matrix_print_1();
extern  matrix * gauss_matrix_print_1_svc();
#define gauss_matrix_print_process 5
extern  matrix * gauss_matrix_print_process_1();
extern  matrix * gauss_matrix_print_process_1_svc();
extern int connection_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_row (XDR *, row*);
extern  bool_t xdr_matrix (XDR *, matrix*);

#else /* K&R C */
extern bool_t xdr_row ();
extern bool_t xdr_matrix ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONNECTION_H_RPCGEN */
